---
title: "Lab 1 Winter 2019"
author: "Maria Schweer-Collins"
date: "January 9, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning = FALSE, message = FALSE}
library(rio)
library(here)
library(tidyverse)
```



```{r load_data, warning = FALSE, message = FALSE}
supd <- import(here("data", "rstats_tweets.rds"), 
            setclass = "tbl.df")
```

#Vizualization 1

```{r commit2, fig.height = 10, fig.width = 10, warning = FALSE, message = FALSE}
d <- supd %>% 
  count(screen_name) %>% 
  arrange(desc(n)) %>% 
  dplyr::slice(1:25)

d <- d %>% 
  mutate(screen_name = fct_reorder(screen_name, n))

p1 <- d %>% 
  ggplot(aes(x = screen_name, y = n)) +
  geom_col(fill = "cornflowerblue") +
  coord_flip() +
  theme_minimal(base_size = 12) +
  ggtitle( "Most prolific #rstats tweeters",
    subtitle = "Top 25 screen names displayed") +
  ylab("Count") +
  xlab("Twitter Screen Name")
p1 + theme_minimal()
```

#Vizualization 2

```{r commit 4, fig.height = 10, fig.width = 10, warning = FALSE, message = FALSE}
round_d <- supd %>%
  mutate(month = lubridate::round_date(created_at, "months")) %>% 
  filter(month < lubridate::as_datetime("2019-01-01 00:00:00"))

tweets <- round_d %>%
  count(month)

bird_plot <- ggplot(tweets, aes(month, n)) + 
  geom_smooth(color = "magenta", se = FALSE, size = 1.25) +
  geom_line(color = "gray40", size = 1.25) +
  geom_area(fill = "cornflowerblue", alpha = .3) +
  ggtitle( "Growth of the #rstats hashtag on twitter over time") + 
  labs(caption = "Data from Mike Kearny, distributed via #tidytuesday",
       y = "Number of #rstats tweets", 
       x = "Year (data summarized by month)")
  

bird_plot + theme_minimal(base_size = 15)
```